name: GraalVM Build

on: [push, pull_request, workflow_dispatch]

jobs:
  validate_gradle_wrapper:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4

  build_gradle:
    needs: validate_gradle_wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macOS-14]
        java: [ '25' ]
        distribution: [ 'graalvm' ]
      fail-fast: false
    name: ${{ matrix.os }} ${{ matrix.java }} (via setup-graalvm)
    steps:
      - name: Git checkout
        uses: actions/checkout@v5
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install secp256k1 with APT
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y libsecp256k1-dev
          echo "LD_LIBRARY_PATH=/usr/lib/$(uname -m)-linux-gnu" >> $GITHUB_ENV
      - name: Install secp256k1 with Homebrew
        if: runner.os == 'macOS'
        run: |
          brew install secp256k1
          echo "DYLD_LIBRARY_PATH=$(brew --prefix secp256k1)/lib" >> $GITHUB_ENV
          echo "JAVA_TOOL_OPTIONS=-Djava.library.path=$(brew --prefix secp256k1)/lib" >> $GITHUB_ENV
      - name: Build (JIT) with Gradle
        run: ./gradlew build
      - name: Run Java & Kotlin Examples
        run: ./gradlew build run runEcdsa
      - name: Build Native Image with Gradle
        run: ./gradlew build secp-examples-java:nativeCompile
      - name: Run Schnorr Native Example
        run: ./secp-examples-java/build/schnorr-example
